[build]
  base = "frontend"
  publish = ".next"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

