[build]
builder = "nixpacks"
buildCommand = "npm run build:with-migration"

[deploy]
startCommand = "bash backend/scripts/deploy.sh && cd backend && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

