[build]
builder = "nixpacks"
buildCommand = "npm run build:with-migration"

[deploy]
startCommand = "cd backend && (npm run prisma:seed || true) && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

