[build]
builder = "nixpacks"
buildCommand = "npm run build:with-migration"

[deploy]
startCommand = "cd backend && npx prisma generate && npx prisma migrate deploy && npm run prisma:seed && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

